### ISSUE TITLE
Reimplement watchtower for greater flexibility

### ISSUE THREAD

**Issue by NullHypothesis** [CAIDA/watchtower-sentry#22]
When an active probing signal has a level shift (e.g., many prefixes are removed from a country due to a geolocation update), we (correctly) trigger an alert, but then, because we don’t use values during an alert to update the history value, the signal never recovers from the ”outage,” and so we end up with lingering incorrect alerts (see https://github.com/CAIDA/watchtower-sentry/issues/21). Addressing this issue involves a fundamental trade-off in how IODA deals with alerts and warrants careful investigation. We should rewrite our watchtower component and make it more flexible to deal with issues of this kind.  In addition, the reimplementation should switch from polling DBATS to consuming the TSK stream.

This task involves new design (and hence some exploration) and subsequent implementation but we have a solid grasp of what is involved.

**Comment by alistairking** [comment]
Largely completed as of 7c97601f38e0227300045037800a1d573dbff327. Bug fixes, additional features in subsequent commits.
